# Generated by Django 4.2.6 on 2023-10-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingdetails',
            options={'verbose_name': 'Shipping Details', 'verbose_name_plural': 'Shipping Details'},
        ),
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
