# Generated by Django 4.2.6 on 2023-10-28 10:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shippingdetails_options_alter_product_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
