# Generated by Django 4.2.6 on 2023-11-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_rename_name_customer_fname_customer_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='item', on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
